// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/libp2p/go-libp2p-core/sec/insecure/pb/plaintext.proto

package plaintext_pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	pb "github.com/libp2p/go-libp2p-core/crypto/pb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exchange struct {
	Id                   []byte        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Pubkey               *pb.PublicKey `protobuf:"bytes,2,opt,name=pubkey" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_0574f2a7e935d85e, []int{0}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Exchange) GetPubkey() *pb.PublicKey {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func init() {
	proto.RegisterType((*Exchange)(nil), "plaintext.pb.Exchange")
}

func init() {
	proto.RegisterFile("github.com/libp2p/go-libp2p-core/sec/insecure/pb/plaintext.proto", fileDescriptor_0574f2a7e935d85e)
}

var fileDescriptor_0574f2a7e935d85e = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0x4c, 0x2a, 0x30, 0x2a, 0xd0, 0x4f, 0xcf,
	0xd7, 0x85, 0xb0, 0x74, 0x93, 0xf3, 0x8b, 0x52, 0xf5, 0x8b, 0x53, 0x93, 0xf5, 0x33, 0xf3, 0x8a,
	0x53, 0x93, 0x4b, 0x8b, 0x52, 0xf5, 0x0b, 0x92, 0xf4, 0x0b, 0x72, 0x12, 0x33, 0xf3, 0x4a, 0x52,
	0x2b, 0x4a, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x90, 0x04, 0x92, 0xa4, 0xcc, 0x09,
	0x9a, 0x97, 0x5c, 0x54, 0x59, 0x50, 0x92, 0x0f, 0x32, 0x09, 0xc2, 0x82, 0x18, 0xa3, 0xe4, 0xc1,
	0xc5, 0xe1, 0x5a, 0x91, 0x9c, 0x91, 0x98, 0x97, 0x9e, 0x2a, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0xc4, 0x94, 0x99, 0x22, 0xa4, 0xc3, 0xc5, 0x56, 0x50, 0x9a,
	0x94, 0x9d, 0x5a, 0x29, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa2, 0x07, 0xd3, 0x9a, 0xa4,
	0x17, 0x50, 0x9a, 0x94, 0x93, 0x99, 0xec, 0x9d, 0x5a, 0x19, 0x04, 0x55, 0x03, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x19, 0x12, 0x32, 0xe2, 0xd3, 0x00, 0x00, 0x00,
}
